"""
Mathematica exporter for symbolic dynamical systems.

This module provides exporters for converting symbolic systems to
Mathematica notebook format.
"""

from typing import Any, List, Optional, Union, TYPE_CHECKING

from kinopulse.export.base import ValidationResult

if TYPE_CHECKING:
    from kinopulse.core.system import DynamicalSystem
    from kinopulse.export.metadata import ExportMetadata
    import sympy as sp


class MathematicaExporter:
    """Exporter for Mathematica format.

    Converts symbolic dynamical systems to Mathematica code suitable for
    analysis in Mathematica or Wolfram Language environments.
    """

    def __init__(self):
        """Initialize Mathematica exporter."""
        pass

    def export(
        self,
        system: 'DynamicalSystem',
        metadata: 'ExportMetadata',
        **kwargs: Any
    ) -> str:
        """Export system to Mathematica format.

        Args:
            system: Dynamical system to export
            metadata: Export metadata
            **kwargs: Additional options:
                - include_parameters: Include parameter definitions (default True)
                - include_output: Include output equations (default True)
                - include_jacobian: Include Jacobian computation (default True)

        Returns:
            Mathematica code string

        Raises:
            ValueError: If system is not symbolic
            RuntimeError: If export fails
        """
        try:
            import sympy as sp
        except ImportError:
            raise ImportError("sympy required for Mathematica export")

        # Check if system has symbolic capabilities
        if not hasattr(system, 'symbolic_dynamics'):
            raise ValueError(
                "System must have symbolic dynamics for Mathematica export"
            )

        # Extract options
        include_parameters = kwargs.get('include_parameters', True)
        include_output = kwargs.get('include_output', True)
        include_jacobian = kwargs.get('include_jacobian', True)

        # Build Mathematica content
        lines = []

        # Header comment
        lines.append(f"(* System: {metadata.system_name} *)")
        lines.append(f"(* Generated by KinoPulse {metadata.kinopulse_version} *)")
        lines.append("")

        # State variable declarations
        state_names = metadata.state_names or [
            f"x{i+1}" for i in range(metadata.state_dim)
        ]
        lines.append("(* State variables *)")
        state_list = "{" + ", ".join(state_names) + "}"
        lines.append(f"stateVars = {state_list};")
        lines.append("")

        # Input variable declarations if present
        if metadata.input_dim and metadata.input_dim > 0:
            input_names = metadata.input_names or [
                f"u{i+1}" for i in range(metadata.input_dim)
            ]
            input_list = "{" + ", ".join(input_names) + "}"
            lines.append("(* Input variables *)")
            lines.append(f"inputVars = {input_list};")
            lines.append("")

        # Parameters
        if include_parameters and hasattr(system, 'parameters'):
            lines.append("(* Parameters *)")
            param_lines = self._render_parameters(system)
            lines.extend(param_lines)
            lines.append("")

        # Dynamics equations
        lines.append("(* Dynamics equations *)")
        dynamics_lines = self._render_dynamics(system, state_names, metadata)
        lines.extend(dynamics_lines)
        lines.append("")

        # Output equations
        if include_output and metadata.output_dim and metadata.output_dim > 0:
            if hasattr(system, 'symbolic_output'):
                lines.append("(* Output equations *)")
                output_lines = self._render_output(system, metadata)
                lines.extend(output_lines)
                lines.append("")

        # Jacobian computation
        if include_jacobian:
            lines.append("(* Jacobian matrix *)")
            jacobian_lines = self._render_jacobian(state_names)
            lines.extend(jacobian_lines)
            lines.append("")

        return "\n".join(lines)

    def _render_parameters(
        self,
        system: Any
    ) -> List[str]:
        """Render parameter definitions in Mathematica.

        Args:
            system: Dynamical system

        Returns:
            List of Mathematica lines
        """
        lines = []

        if not hasattr(system, 'parameters'):
            return lines

        parameters = system.parameters()

        if not parameters:
            return lines

        for param_name, param_value in parameters.items():
            # Format parameter value
            if isinstance(param_value, (int, float)):
                value_str = self._format_number(param_value)
            else:
                value_str = str(param_value)

            lines.append(f"{param_name} = {value_str};")

        return lines

    def _render_dynamics(
        self,
        system: Any,
        state_names: List[str],
        metadata: 'ExportMetadata'
    ) -> List[str]:
        """Render dynamics equations in Mathematica.

        Args:
            system: Dynamical system
            state_names: State variable names
            metadata: Export metadata

        Returns:
            List of Mathematica lines
        """
        lines = []

        if not hasattr(system, 'symbolic_dynamics'):
            return lines

        # Get symbolic dynamics
        dynamics = system.symbolic_dynamics()

        # Convert to Mathematica format
        dynamics_mathematica = self._expr_to_mathematica(dynamics)

        lines.append(f"dynamics = {dynamics_mathematica};")

        return lines

    def _render_output(
        self,
        system: Any,
        metadata: 'ExportMetadata'
    ) -> List[str]:
        """Render output equations in Mathematica.

        Args:
            system: Dynamical system
            metadata: Export metadata

        Returns:
            List of Mathematica lines
        """
        lines = []

        if not hasattr(system, 'symbolic_output'):
            return lines

        # Get symbolic output
        output = system.symbolic_output()

        # Convert to Mathematica format
        output_mathematica = self._expr_to_mathematica(output)

        lines.append(f"outputEqns = {output_mathematica};")

        return lines

    def _render_jacobian(
        self,
        state_names: List[str]
    ) -> List[str]:
        """Render Jacobian computation template in Mathematica.

        Args:
            state_names: State variable names

        Returns:
            List of Mathematica lines
        """
        lines = []

        # Jacobian computation template
        state_list = "{" + ", ".join(state_names) + "}"
        lines.append(f"jacobianMatrix = D[dynamics, {state_list}];")

        return lines

    def _expr_to_mathematica(
        self,
        expr: Union['sp.Expr', List['sp.Expr']]
    ) -> str:
        """Convert SymPy expression to Mathematica syntax.

        Args:
            expr: SymPy expression or list of expressions

        Returns:
            Mathematica code string
        """
        try:
            import sympy as sp
            from sympy.printing.mathematica import mathematica_code
        except ImportError:
            raise ImportError("sympy required for Mathematica export")

        if isinstance(expr, list):
            # Vector expression - use Mathematica list notation
            components = [self._expr_to_mathematica(e) for e in expr]
            return "{" + ", ".join(components) + "}"

        # Single expression - use SymPy's Mathematica printer
        return mathematica_code(expr)

    def _format_number(self, value: float) -> str:
        """Format number for Mathematica.

        Args:
            value: Numeric value

        Returns:
            Formatted string
        """
        # Use scientific notation for very small/large numbers
        if abs(value) < 1e-10 and value != 0:
            return f"{value:.15e}".replace('e', '*^')
        elif abs(value) > 1e10:
            return f"{value:.15e}".replace('e', '*^')
        else:
            return str(value)

    def validate(
        self,
        exported: Any,
        original: 'DynamicalSystem',
        tolerance: float = 1e-6
    ) -> ValidationResult:
        """Validate exported Mathematica code.

        For Mathematica exports, validation checks:
        - Presence of required elements (state variables, dynamics)
        - Balanced delimiters
        - Comment syntax

        Args:
            exported: Exported Mathematica code string
            original: Original dynamical system
            tolerance: Not used for Mathematica validation

        Returns:
            ValidationResult

        Note:
            Mathematica exports cannot be numerically validated without
            a Mathematica runtime, so this returns a basic syntax check.
        """
        if not isinstance(exported, str):
            return ValidationResult(
                passed=False,
                max_error=0.0,
                mean_error=0.0,
                type_mismatch=True,
                error_details="Expected string for Mathematica export"
            )

        errors = []

        # Check for balanced delimiters
        checks = {
            '(*': '*)',
            '{': '}',
            '[': ']',
            '(': ')',
        }

        for open_delim, close_delim in checks.items():
            open_count = exported.count(open_delim)
            close_count = exported.count(close_delim)
            if open_count != close_count:
                errors.append(
                    f"Unbalanced delimiters: {open_count} '{open_delim}' "
                    f"vs {close_count} '{close_delim}'"
                )

        # Check for essential elements
        if 'stateVars' not in exported:
            errors.append("No state variable declaration found")

        if 'dynamics' not in exported:
            errors.append("No dynamics equations found")

        # Check for comment syntax
        if '(*' in exported and '*)' not in exported:
            errors.append("Incomplete comment syntax")

        passed = len(errors) == 0

        return ValidationResult(
            passed=passed,
            max_error=0.0,  # Not applicable for Mathematica
            mean_error=0.0,  # Not applicable for Mathematica
            error_details="; ".join(errors) if errors else None,
            test_cases=1
        )


def export_to_mathematica(
    system: 'DynamicalSystem',
    metadata: 'ExportMetadata',
    **kwargs: Any
) -> str:
    """Export system to Mathematica format.

    Convenience function for creating a MathematicaExporter and exporting.

    Args:
        system: Dynamical system to export
        metadata: Export metadata
        **kwargs: Additional options passed to MathematicaExporter.export()

    Returns:
        Mathematica code string
    """
    exporter = MathematicaExporter()
    return exporter.export(system, metadata, **kwargs)
