copy /b dh_src\kinopulse.core.* dh_src\all_core.txt
copy /b dh_src\kinopulse.utils.* dh_src\all_utils.txt
copy /b dh_src\kinopulse.symbolic.* dh_src\all_symbolic.txt
copy /b dh_src\kinopulse.analysis.* dh_src\all_analysis.txt
copy /b dh_src\kinopulse.numeric.* dh_src\all_numeric.txt
copy /b dh_src\kinopulse.solvers.* dh_src\all_solvers.txt
copy /b dh_src\kinopulse.neural.* dh_src\all_neural.txt
copy /b dh_src\kinopulse.hybrid.* dh_src\all_hybrid.txt
copy /b dh_src\kinopulse.identification.* dh_src\all_identification.txt
copy /b dh_src\kinopulse.control.* dh_src\all_control.txt
copy /b dh_src\kinopulse.export.* dh_src\all_export.txt
copy /b dh_src\kinopulse.viz.* dh_src\all_viz.txt
